trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:
  - script: echo Hello world!
    displayName: 'Placeholder step'
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(serviceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group Example \
          --template-file bicep/main.bicep